### PR TITLE
fix: serialize to deployment spec

### LINKED ISSUE #195: [IR: turbine-js] Fix spec structure

### PR DESCRIPTION
**Pull request by jmar910**
Closes #195 

spec now looks like:

```js
    {
      connectors: [
        {
          resource: "a-source",
          type: "source",
          collection: "source_collection",
          config: { SOURCE_CONFIG: "hey" },
        },
        {
          resource: "a-dest",
          type: "destination",
          collection: "dest_collection",
          config: { DEST_CONFIG: "bye" },
        },
      ],
      functions: [{ name: "aFn-12345678", image: "imageName" }],
      secrets: { A_ENV_VAR: "sleeptokenrocks" },
      definition: {
        git_sha: "123456789",
        metadata: {
          turbine: {
            language: "js",
            version: "1.0.0",
          },
          spec_version: "0.1.0",
        },
      },
    }
```

## Testing
+ Updated format in automated test file
+ `turbine-js-cli clideploy` command

### CODE REVIEW

File: packages/turbine-js-cli/test/unit/platform-v2-test.ts [hunk 1]
```diff
@@ -96,7 +90,7 @@ QUnit.module("Unit | PlatformV2Runtime", () => {
     assert.strictEqual(runtime.spec, "0.1.0");
   });
 
-  QUnit.test("#metadata", (assert) => {
+  QUnit.test("#definition", (assert) => {
```
Comment (jayjayjpg) [inline packages/turbine-js-cli/test/unit/platform-v2-test.ts:93]: Nice test case update here as well!

File: packages/turbine-js-cli/test/unit/platform-v2-test.ts [hunk 2]
```diff
@@ -153,7 +151,7 @@ QUnit.module("Unit | PlatformV2Runtime", () => {
     assert.strictEqual(runtime.registeredSecrets.A_ENV_VAR, "sleeptokenrocks");
   });
 
-  QUnit.test("#serializeToDeployment", (assert) => {
+  QUnit.test("#serializeToDeploymentSpec", (assert) => {
```
Comment (jayjayjpg) [inline packages/turbine-js-cli/test/unit/platform-v2-test.ts:154]: This test case is already super helpful for documentation purposes!

**Review by jayjayjpg — APPROVED** [review]
This reads great and thank you for the super quick update! :sparkles:

**Review by raulb — APPROVED** [review]
Looks great, thank you @jmar910 !
